// Reproducible, original procedural soundscapes. No streamed or sampled recordings.
import fs from "node:fs";
import vm from "node:vm";
fs.mkdirSync("public/audio", { recursive: true });
fs.mkdirSync("public/icons", { recursive: true });
const context = {};
vm.createContext(context);
vm.runInContext(
  fs.readFileSync("node_modules/lamejs/lame.all.js", "utf8"),
  context,
);
let seed = 12345;
const random = () => {
  seed = (seed * 1664525 + 1013904223) >>> 0;
  return seed / 4294967296;
};
const rate = 22050,
  seconds = 20,
  length = rate * seconds;
function generate(kind) {
  const samples = new Float64Array(length);
  let low = 0;
  for (let i = 0; i < length; i++) {
    const t = i / rate,
      n = random() * 2 - 1;
    low = low * 0.975 + n * 0.025;
    let x = 0;
    if (kind === "rain") x = n * 0.16 + low * 0.85;
    if (kind === "ocean")
      x =
        (low * 2.6 + n * 0.025) *
        (0.3 + 0.7 * (0.5 + 0.5 * Math.sin((2 * Math.PI * t) / 10)));
    if (kind === "forest") {
      x = low * 0.5 + n * 0.012;
      const b = t % 4;
      if (b < 0.5)
        x +=
          Math.sin(2 * Math.PI * (1900 * b + 300 * b * b)) *
          0.1 *
          Math.sin((Math.PI * b) / 0.5);
    }
    if (kind === "cafe") {
      x = low * 0.85 + n * 0.013;
      const b = t % 2.5;
      x +=
        Math.sin(2 * Math.PI * 90 * t) *
        0.025 *
        (0.5 + 0.5 * Math.sin(2 * Math.PI * 3 * t));
      if (b < 0.12)
        x += Math.sin(2 * Math.PI * 1600 * b) * Math.exp(-60 * b) * 0.12;
    }
    if (kind === "piano") {
      const notes = [
        261.626, 329.628, 391.995, 493.883, 440, 391.995, 329.628, 293.665,
      ];
      for (let k = 0; k < notes.length; k++) {
        const a = (t - k * 2.5 + seconds) % seconds;
        const env = Math.min(1, a * 80) * Math.exp(-a * 1.1);
        x +=
          env *
          (Math.sin(2 * Math.PI * notes[k] * a) +
            0.35 * Math.sin(2 * Math.PI * notes[k] * 2 * a) +
            0.1 * Math.sin(2 * Math.PI * notes[k] * 3 * a)) *
          0.17;
      }
    }
    // Match boundary with short fades, avoiding clicks at the loop seam.
    const fade = Math.min(1, t / 0.04, (seconds - t) / 0.04);
    samples[i] = x * fade;
  }
  const max = Math.max(...samples.subarray(0, 10000).map(Math.abs));
  const gain = Math.min(1.5, 0.55 / Math.max(0.2, max));
  return Int16Array.from(samples, (x) =>
    Math.max(-32767, Math.min(32767, x * gain * 32767)),
  );
}
for (const kind of ["rain", "ocean", "forest", "cafe", "piano"]) {
  const pcm = generate(kind);
  const encoder = new context.lamejs.Mp3Encoder(1, rate, 64);
  const buffers = [];
  for (let i = 0; i < pcm.length; i += 1152)
    buffers.push(Buffer.from(encoder.encodeBuffer(pcm.subarray(i, i + 1152))));
  buffers.push(Buffer.from(encoder.flush()));
  fs.writeFileSync(`public/audio/${kind}.mp3`, Buffer.concat(buffers));
}
await import("./icons.mjs");
fs.writeFileSync(
  "public/audio/LICENSE.txt",
  `Calm Corner audio assets\n\nThe five MP3 soundscapes are original, deterministic procedural compositions generated by scripts/assets.mjs. They are synthetic interpretations, not field recordings. These audio outputs are dedicated to the public domain under CC0 1.0: https://creativecommons.org/publicdomain/zero/1.0/\n\nThe active breathing cues (inhale.mp3, hold.mp3, exhale.mp3) are project-supplied recordings and are not generated or overwritten by this script. No license for those recordings is assigned by this notice.\n\nLegacy breathing cue WAV files are synthesized from the Malay phrases 'Tarik nafas', 'Tahan', and 'Hembus perlahan' using eSpeak NG (build-time tool, GPL-3.0-or-later). The synthesis engine is not distributed in the app. Source: https://github.com/espeak-ng/espeak-ng ; JS build: https://github.com/ianmarmour/espeak-ng.js\n\nFonts: DM Sans and Lora, SIL Open Font License, bundled via @fontsource. Icons: Lucide, ISC license.\n`,
);
console.log(
  "Generated five MP3 soundscapes and four installation icons; preserved custom breathing cues.",
);
